<link rel="stylesheet" type="text/css" href="css/styles.css">
<footer class="clearfix"><!-- Defining the footer section of the page -->
    <div class="container">
        Venieri Nicolò &copy; 2023 <a class="link" href="https://www.linkedin.com/in/nicol%C3%B2-venieri-5b14071a1/">My linkedin profile</a><br />
        <a class="link" href="https://www.instagram.com/nicolovenieri/">My ig profile</a>
    </div>
</footer>
